### PR TITLE
Feature/upgrade jh 781

### PR DESCRIPTION
**Pull request by UserNobody14**
Just like my previous pull request except one increment higher, bumps the dependencies up to jhipster 7.8.1

### CODE REVIEW

**Comment by amanganiello90** [comment]
Hi,
Thanks for the interest.
Updating to new jhipster is not so simple, in fact we need to resolve the actual problem of integration tests not running in github actions.

**Comment by pahlers** [comment]
@amanganiello90 Can we trigger the build again? The pipelines says "The logs for this run have expired and are no longer available."

**Comment by pahlers** [comment]
Found another pipeline which have logs

**Comment by pahlers** [comment]
It seems the module `chalk` isn't been found by the application.

**Comment by amanganiello90** [comment]
Chalk is already added in package.json : https://github.com/jhipster/generator-jhipster-nodejs/blob/7002525011ef61db674ea8997a7dabf7fdd497ec/package.json#L56

**Comment by thiago-a-delgado** [comment]
> Hi, Thanks for the interest. Updating to new jhipster is not so simple, in fact we need to resolve the actual problem of integration tests not running in github actions.

Hello @amanganiello90!
I would like to contribute to the NHipster project.
What is the most up-to-date branch or commit, which tries to use a version of JHipster >= 7.7.x and that is minimally stable?
I understand that this branch or commit may still have some errors, but I would like to know where to try to improve the NHipster project from.

**Comment by DanielFran** [comment]
Superseded by https://github.com/jhipster/generator-jhipster-nodejs/pull/301

Thanks anyway @UserNobody14  for the contribution

**Pull request closed without merging**
