### PR TITLE
Issue136

### PR DESCRIPTION
**Pull request by Aragonbn90**
Hi @amanganiello90 
I've done #136. Please help me to check it.

### CODE REVIEW

**Comment by amanganiello90** [comment]
All good! wonderful! But I have only a question about postgres database.

**Comment by amanganiello90** [comment]
I have tested and added the correct value for postgres (postegresql on prompt). See the https://github.com/jhipster/generator-jhipster-nodejs/pull/144. Thanks a lot @Aragonbn90 !!!
You can claim your bounty bug following these steps:
- https://opencollective.com/generator-jhipster/expenses/new
Link this PR (id 142)

**Comment by jdubois** [comment]
Bug bounty paid, congrats @Aragonbn90 !

**Comment by Aragonbn90** [comment]
@jdubois I created wrong type with reimbursement. I've created an invoice at https://opencollective.com/generator-jhipster/expenses/20165
Please approve it. Thank you.

**Pull request merged**
