### PR TITLE
Do not read user password from DB closes #232

### LINKED ISSUE #232: Remove in query user api the unencrypted password exposed
**Describe the bug**
At numerous places in the application, the value of the password property of the user entity are delivered in plain text. This affects (incomplete):
- GET /api/admin/users
- GET /api/account

The password should not be readable to anyone, not even the admin. The password should be at least encrypted, but it would be better if it was not included in the serialized user object at all. 

**To Reproduce**

1. Generate a new app via nhipster
2. Select the default option for every question
3. Login as admin
4. Go to User Management
5. Open Dev Tools Check the returned data for the listed endpoints

**Expected behavior**
The password is not part of the serialized user object.

**Screenshots**
Screenshot 2021-05-31 at 10 58 56

**Desktop (please complete the following information):**

-   OS: iOS 11.3
-   NHipster Version 2.0.0-beta.1

**NHipster configuration**

**Additional context**
I discovered the problem while working on #214

### PR DESCRIPTION
**Pull request by glutengo**

### CODE REVIEW

**Comment by amanganiello90** [comment]
I see that you have disabled encryption on typeOrm. So we have to find an alternative way to obscure that value. Therefore the PR is not complete.

**Comment by glutengo** [comment]
@amanganiello90 the change does not mean that the encryption is disabled. The change just means that whenever the user is read from the database, the password column is not included in the query. The password is still encrypted.

**Review by amanganiello90 — CHANGES_REQUESTED** [review]
You have to fix user e2e test on https://github.com/jhipster/generator-jhipster-nodejs/blob/058b1da787658f94c3ca6e58de6ce92c95289490/generators/server/templates/server/e2e/user.e2e-spec.ts.ejs#L29

The test integration pipeline fails for that.

**Comment by glutengo** [comment]
@amanganiello90 thank you for pointing out and apologies for not running them before submitting the PR!
I have made some adjustments which fixed the e2e tests for a nhipster project I generated on my local machine.

Is there any way to run the full pipeline on a local machine?

**Comment by amanganiello90** [comment]
Hi @glutengo , you have to follows the steps of the the integration-test yml files: https://github.com/jhipster/generator-jhipster-nodejs/tree/main/.github/workflows

They use the templates defined in https://github.com/jhipster/generator-jhipster-nodejs/tree/main/test-integration/samples .

The configuration are performed by sh files in the upper folder.

**Comment by glutengo** [comment]
@amanganiello90 should be good now, pipeline checks have passed

**Pull request merged**
