### PR TITLE
Feature/vue issue158

### PR DESCRIPTION
**Pull request by amanganiello90**
Jhipster 7.0.0 upgrade with vue support:
- jwt/oauth2 security tested with all client frameworks (angular, react and vue)
- JDL integration tests (on pipeline) with sql, mongodb, all clients and security
- Fixed unit test and e2e tests for client and server according jhipster 7.0.0 upgrade (user controller changed on rest api endpoint, that is for admin or public)

This Nhipster blueprint upgrade has required a lot of stuff.

### CODE REVIEW

**Comment by amanganiello90** [comment]
@mraible any feedbacks?

**Comment by mraible** [comment]
I haven't had a chance to look yet. Maybe tomorrow. In the meantime, maybe other @jhipster/hipsters can help?

**Comment by amanganiello90** [comment]
Any news?

**Comment by mraible** [comment]
If it works, ship it! 🚢

**Pull request merged**
